const books = [
  {
    title: "Queen of the Damned",
    author: "Clemmie Corkitt",
    category: "Scifi",
    year: 1988,
    pages: 82,
    cover: "#2341d7",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Bully",
    author: "Bobby Ebdin",
    category: "Romance",
    year: 2002,
    pages: 89,
    cover: "#493408",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Bright Victory",
    author: "Cindie Garnsworthy",
    category: "Educational",
    year: 2001,
    pages: 83,
    cover: "#ed4889",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Patsy, The",
    author: "Olvan Boulds",
    category: "Romance",
    year: 1966,
    pages: 98,
    cover: "#eee0a9",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Fresh Guacamole",
    author: "Cari Thurber",
    category: "Romance",
    year: 2011,
    pages: 94,
    cover: "#0d41bc",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Lille Fridolf and I",
    author: "Nissy Awin",
    category: "Scifi",
    year: 1995,
    pages: 86,
    cover: "#fdd39d",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "How the West Was Fun",
    author: "Alvan Moorerud",
    category: "Scifi",
    year: 2000,
    pages: 91,
    cover: "#2a62f1",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Osmosis Jones",
    author: "Fidela Bedward",
    category: "Scifi",
    year: 2002,
    pages: 90,
    cover: "#e49b97",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Celine: Through the Eyes of the World",
    author: "Ansley Crush",
    category: "Educational",
    year: 2010,
    pages: 82,
    cover: "#586179",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Sharky's Machine",
    author: "Kinnie Neame",
    category: "Romance",
    year: 2001,
    pages: 89,
    cover: "#475834",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Last Time I Saw Paris, The",
    author: "Kimberly Muro",
    category: "Romance",
    year: 1958,
    pages: 87,
    cover: "#09cbd6",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Broken Arrow",
    author: "Wilhelmina Turmall",
    category: "Romance",
    year: 2007,
    pages: 86,
    cover: "#353b85",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Valet, The (La doublure)",
    author: "Salome Tibbotts",
    category: "Educational",
    year: 1993,
    pages: 96,
    cover: "#b30ad8",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "33 Scenes from Life (33 sceny z zycia)",
    author: "Davidde McPhilip",
    category: "Educational",
    year: 2011,
    pages: 90,
    cover: "#20f30d",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title:
      "Mona and the Time of Burning Love (Mona ja palavan rakkauden aika))",
    author: "Berna Noller",
    category: "Romance",
    year: 2008,
    pages: 99,
    cover: "#f37125",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Role/Play",
    author: "Melessa Quincee",
    category: "Scifi",
    year: 2007,
    pages: 81,
    cover: "#fbde2a",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Great Race, The",
    author: "Risa Raeburn",
    category: "Scifi",
    year: 2006,
    pages: 98,
    cover: "#4411ca",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "People That Time Forgot, The",
    author: "Kari Vasilyevski",
    category: "Romance",
    year: 2000,
    pages: 87,
    cover: "#027c52",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title: "Dave Chappelle: For What it's Worth",
    author: "Mahalia Aspital",
    category: "Scifi",
    year: 1994,
    pages: 90,
    cover: "#443b28",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
  {
    title:
      "Beat That My Heart Skipped, The (battre mon coeur s'est arrêté, De)",
    author: "Antin Maymand",
    category: "Scifi",
    year: 2008,
    pages: 87,
    cover: "#81e399",
    chapters: [
      { title: "Hello world", no: 1 },
      { title: "there is hope", no: 2 },
      { title: "lets do this", no: 3 },
    ],
  },
];

module.exports = books;
